@startuml

class Company {
    _id: ObjectId
    name: String
    address: String
    website: String
    description: String
    tel: String
}

class Appointment {
    _id: ObjectId
}

Company -- Appointment : has

@enduml